# 是否启用插件
# 默认启用
enable_mc_qq: true

# 请在冒号后填写 WebSocket 服务的地址端口号。
# 只填写数字即可。
# 冒号后需要空一格！
# 若不填写，则地址默认为 127.0.0.1 ，端口默认为 8765
websocket_hostname: 127.0.0.1
websocket_port: 8765

# 发送到群消息中，玩家昵称与消息之间的符号
# 默认为 “说：”
# 例如：
#   17TheWord说： 你好
say_way: "说："

# 是否启用 玩家死亡事件监听
# 开启后，当玩家死亡时，Bot 会推送信息
# 默认启用
death_message: true

# 是否启用 加入/离开 服务器监听
# 开启后，当玩家 加入/离开 服务器时，Bot 会推送信息
# 默认打开
# 例如：
#   17TheWord 加入了服务器
#   17TheWord 离开了服务器
join_quit: true

# 服务器名称
# 当有多个服务器连接到 Bot 时，用于区分。
# 如果是多个服务器，请务必对各个服务器设置不同的服务器名称。
# 默认值为：Server
server_name: "Server"

# 是否启用 群名/频道名 前缀
# Rcon 版不适用：
#   因为Rcon版本发送至服务端的消息并不受该配置文件控制。
#
# 开启后，当消息推送到游戏中会携带 群名/频道名。
# 此开关在 NoneBot 端也有，但 NoneBot 端决定是否发送过来名称。
# 发送名称需要 Bot 请求 API，可能会对服务器性能有影响。
# 例如：
#   测试群 17TheWord 说：你好
#   测试频道/测试子频道 17TheWord 说：你好
display_groupname: false

# 日志路径
# 仅日志读取程序可用
# Windows 请用 ".\\logs\\"
# Linux 请用 "./logs/"
log_local: "./logs/"

# 日志名称
# 仅日志读取程序可用
# 若日志名称不同，请手动修改，一般为：latest.log
log_name: "latest.log"
